version: "3.1"
services:
  webserver:
    image: "nginx:alpine"
    working_dir: /app
    volumes:
      - ".:/app"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"

  php-fpm:
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - ".:/app"
      - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini"

  postgres:
    image: "postgres:15-alpine"
    working_dir: /app
    volumes:
      - ".:/app"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db_api_app
    ports:
      - "20000:5432"
