<?php

use App\Http\Controllers\Api\v1\DeliveryController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

/* This code is defining a route for the root URL of the API (i.e., "/"). When a GET request is made to
this URL, the function specified in the second argument is executed. This function returns a JSON
response with a message welcoming the user to the API. */

Route::get('/', function () {
    return response()->json([
        'message' => 'Bem-vindo a API da Itarget escolha uma versão e comece a usar <3'
    ]);
});

/* This code is defining a group of routes with a prefix of "v1". Within this group, there is a
resource route for "deliveries" that maps to the methods in the DeliveryController class. This means
that the routes for CRUD operations (create, read, update, delete) on deliveries will be
automatically generated by Laravel based on the methods in the DeliveryController class. */

Route::prefix('v1')->group(function () {
    Route::resource('deliveries', DeliveryController::class);
});
